name: premier_analysis
channels:
- defaults
dependencies:
- python=3.8
- pip:
  - azureml-defaults
  - matplotlib
  - pandas==1.1.5
  - argparse
  - joblib
  - scikit-learn
  - azureml-sdk
  - openpyxl
  - tensorflow
  - keras-tuner