channels:
- anaconda
- default
dependencies:
- python=3.8
- pip:
  - azureml-defaults
  - matplotlib
  - pandas
  - argparse
  - joblib
  - inference-schema[numpy-support]
  - scikit-learn
  - azureml-sdk
  - openpyxl
  - tensorflow
