---
title: MISA Results Vis
author: Sean Browning <sbrowning (at) cdc (dot) gov>
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        df_print: paged
        toc: Yes
        toc_float: Yes
        theme: readable
---

```{r knit_opts, include=FALSE}
knitr::opts_chunk$set(
  include = TRUE,
  echo = FALSE, warning = FALSE, message = FALSE,
  dev = "CairoSVG",
  knitr.kable.NA = ""
)
```

```{r lib}
library(dplyr)
library(tidyr)
library(forcats)
library(readxl)
library(ggplot2)
library(ggthemr)

ggthemr("fresh", layout = "scientific")
```

```{r data in}
# === Path handling
# If we're knitting, use one directory down
if (isTRUE(getOption("knitr.in.progress"))) {
  data_dir <- file.path("..", "data")
  output_dir <- file.path("..", "output")
} else {
  data_dir <- file.path("data")
  output_dir <- file.path("output")
}

results_file <- file.path(data_dir, "lgr_coefs.xlsx")
results_sheets <- readxl::excel_sheets(results_file)
read_results <- function(sheet, path = results_file) {
  out <- read_xlsx(path, sheet) %>%
    mutate(outcome = sheet)
  
  return(out)
}

results <- lapply(results_sheets, read_results) %>%
  bind_rows() %>%
  mutate(
    outcome = recode(
      outcome,
      "misa_pt" = "HS",
      "icu" = "ICU",
      "death" = "Death"
      ))
```

```{r pivot and plot, fig.width = 13, fig.height = 10}
for (out in split(results, ~outcome)) {
  outcome <- unique(out[["outcome"]])

  plot_out <- out |>
    arrange(aOR) |>
    mutate(feature = fct_inorder(feature)) |>
    ggplot(aes(x = aOR, y = feature, color = log10(aOR))) +
    geom_point(show.legend = FALSE) +
    scale_color_distiller(palette = "RdBu", type = "div") +
    geom_vline(aes(xintercept = 1)) +
    scale_x_log10() +
    labs(
      # x = expression(log[10](aOR)),
      x = "aOR",
      y = "Feature",
      title = sprintf("Logistic Regression Results, %s", outcome)
    )


  print(plot_out)
}
  ```